name: vet scan

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  run-vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run vet
        id: vet
        uses: safedep/vet-action@v1
        with:  
          policy: .github/vet/policy.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF
        if: steps.vet.outputs.report != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.vet.outputs.report }}
          category: vet